services:
  - type: web
    name: school-roster-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: CHROME_BIN
        value: /usr/bin/chromium-browser
      - key: GOOGLE_CHROME_SHIM
        value: /usr/bin/chromium-browser
